development:
  adapter: postgresql
  encoding: utf8
  database: prosody_development
  pool: 5
  username: appacademy
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: prosody_test
  pool: 5
  username: appacademy
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: prosody_production
  pool: 5
  username: appacademy
  password:

cucumber:
  <<: *TEST
